server:
  port: 8083

spring:
  application:
    name: notification-service
  kafka:
    bootstrap-servers: kafka:9092
    retryKey: retry
    errorKey: error
    consumer:
      topics:
        subscription-status-updated:
          topic: subscription-status-updated.0
          retryTopic: ${spring.kafka.consumer.topics.subscription-status-updated.topic}.${spring.application.name}.${spring.kafka.retryKey}
          errorTopic: ${spring.kafka.consumer.topics.subscription-status-updated.topic}.${spring.application.name}.${spring.kafka.errorKey}
          consumerGroup: ${spring.application.name}-subscription-status-updated
          consumerGroupRetry: ${spring.application.name}-subscription-status-updated-retry
          concurrencyLevel: 1
          autoOffsetReset: latest
  datasource:
    url: jdbc:postgresql://postgres:5432/subscription_db
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true

logging:
  level:
    root: INFO
    com.notification: DEBUG
    org.springframework.kafka: DEBUG 