apiVersion: v1
kind: ConfigMap
metadata:
  name: notification-service-config
data:
  spring.datasource.url: "jdbc:postgresql://postgres:5432/subscription_db"
  spring.kafka.bootstrap-servers: "kafka:9092" 