apiVersion: v1
kind: Secret
metadata:
  name: notification-service-secrets
type: Opaque
data:
  spring.datasource.username: cG9zdGdyZXM=  # postgres
  spring.datasource.password: cG9zdGdyZXM=  # postgres 